version: '3'

services:
  sharq:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - LOG_LEVEL=warning
      - ACCESS_LOG=
    ports:
      - 8000:80
    depends_on:
      - redis
  redis:
    image: redis:5.0
    ports:
      - '6379:6379'
    volumes:
      - ./docker/config/redis.conf:/etc/redis/redis.conf
    environment:
      - IP=0.0.0.0
      - REDIS_PASSWORD=hello
    command: ["redis-server", "/etc/redis/redis.conf"]
