version: '3'

services:
  sharq:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    # volumes:
    #   - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: redis:5.0
    ports:
      - '6379:6379'
    volumes:
      - ./docker/config/redis.conf:/etc/redis/redis.conf
    environment:
      - IP=0.0.0.0
      - REDIS_PASSWORD=hello
    command: ["redis-server", "/etc/redis/redis.conf"]
